# Sample file just for compiling
# Add your own keys if you want to test internal functions

sample_identity_key = ""
sample_nbe_list_devices_response = ""
sample_canonic_device_id = ""
sample_pin = ""
sample_pin_salt = ""
sample_locally_encrypted_recovery_key = ""
sample_encrypted_application_key = ""
sample_encrypted_security_domain_key = ""
sample_encrypted_shared_key = ""
sample_encrypted_owner_key = ""
sample_encrypted_account_key = ""
sample_encrypted_eik = ""
sample_account_key = ""
sample_location_data = ""
sample_own_report = ""
sample_foreign_report = ""
sample_device_update = ""
sample_pk_secret_key = ""
sample_pk_prefix = ""
sample_pk_encoded_point = ""
sample_pk_plaintext = ""
sample_pk_encoded_point_hmac = ""
