# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProtoDecoders/LocationReportsUpload.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'ProtoDecoders/LocationReportsUpload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ProtoDecoders import Common_pb2 as ProtoDecoders_dot_Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)ProtoDecoders/LocationReportsUpload.proto\x1a\x1aProtoDecoders/Common.proto\"|\n\x15LocationReportsUpload\x12\x18\n\x07reports\x18\x01 \x03(\x0b\x32\x07.Report\x12\'\n\x0e\x63lientMetadata\x18\x02 \x01(\x0b\x32\x0f.ClientMetadata\x12\x0f\n\x07random1\x18\x03 \x01(\x04\x12\x0f\n\x07random2\x18\x04 \x01(\x04\"\x86\x01\n\x06Report\x12%\n\radvertisement\x18\x01 \x01(\x0b\x32\x0e.Advertisement\x12\x13\n\x04time\x18\x04 \x01(\x0b\x32\x05.Time\x12@\n\x1alocationAndRotationOffsets\x18\x06 \x01(\x0b\x32\x1c.LocationsAndRotationOffsets\"U\n\rAdvertisement\x12\x1f\n\nidentifier\x18\x05 \x01(\x0b\x32\x0b.Identifier\x12#\n\x1bunwantedTrackingModeEnabled\x18\x06 \x01(\r\"\\\n\x1bLocationsAndRotationOffsets\x12=\n\x19locationAndRotationOffset\x18\n \x03(\x0b\x32\x1a.LocationAndRotationOffset\"2\n\nIdentifier\x12\x0b\n\x03\x65id\x18\x06 \x01(\x0c\x12\x17\n\x0f\x63\x61nonicDeviceId\x18\x07 \x01(\x0c\"<\n\x0e\x43lientMetadata\x12*\n\x07version\x18\x02 \x01(\x0b\x32\x19.ClientVersionInformation\"7\n\x18\x43lientVersionInformation\x12\x1b\n\x13playServicesVersion\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoDecoders.LocationReportsUpload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONREPORTSUPLOAD']._serialized_start=73
  _globals['_LOCATIONREPORTSUPLOAD']._serialized_end=197
  _globals['_REPORT']._serialized_start=200
  _globals['_REPORT']._serialized_end=334
  _globals['_ADVERTISEMENT']._serialized_start=336
  _globals['_ADVERTISEMENT']._serialized_end=421
  _globals['_LOCATIONSANDROTATIONOFFSETS']._serialized_start=423
  _globals['_LOCATIONSANDROTATIONOFFSETS']._serialized_end=515
  _globals['_IDENTIFIER']._serialized_start=517
  _globals['_IDENTIFIER']._serialized_end=567
  _globals['_CLIENTMETADATA']._serialized_start=569
  _globals['_CLIENTMETADATA']._serialized_end=629
  _globals['_CLIENTVERSIONINFORMATION']._serialized_start=631
  _globals['_CLIENTVERSIONINFORMATION']._serialized_end=686
# @@protoc_insertion_point(module_scope)
